### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kasakui** [RyanLeeLY/FastKV#2]
Hi,I crashed in
    size_t mmsize = MAX(mapSize, _initialMMSize);
    _mmptr = mmap(NULL, mmsize,  PROT_READ | PROT_WRITE, MAP_FILE | MAP_SHARED, _fd, 0);
    if (_mmptr == MAP_FAILED) {
        NSCAssert(NO, @"[FastKV] Create mmap failed: %d", errno);
        return NO;
    }
How to fix it?

**Comment by RyanLeeLY** [comment]
Can you show me your console log info?

**Comment by kasakui** [comment]
Thanks for your reply.
This is console log info:
 *** Assertion failure in -[FastKV mapWithSize:]()
It happens on iPhone 6s,iOS11.4.1.
I called [FastKV defaultFastKV] on launching.

**Comment by RyanLeeLY** [comment]
[FastKV] Create mmap failed: %d", errno

What's the value of variable 'errno'?

**Comment by kasakui** [comment]
0

**Comment by RyanLeeLY** [comment]
So weird. If mmap failed, errno should be larger than 0.
Can you give me your source code  if you can reproduce the problem.

**Comment by kasakui** [comment]
I debug again.
This time 'errno' is 12

**Comment by RyanLeeLY** [comment]
#define	ENOMEM		12		/* Cannot allocate memory */

Maybe the memory size is out of limitation. What's the size of your mmap?

**Comment by kasakui** [comment]
My iPhone 7 Plus's size of 'mmsize' is 536870912.
iPhone 6s is 2147483648 and crash.

**Comment by RyanLeeLY** [comment]
2147483648 is too large. FastKV will read the whole mmap file to memory. I don't recommend using FastKV to store large object or too many objects. FastKV is designed as a real-time storage, so it is not like a common disk-memory cache.
